-- ==========================================
-- TODOS TABLE SETUP
-- ==========================================
-- This script creates a todos table with row level security
-- and includes sample data for testing

-- Create the todos table
create table todos (
  id bigint generated by default as identity primary key,
  title text,
  is_complete boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table todos enable row level security;

-- Create policy to allow anyone to view todos
create policy "Anyone can view todos" on todos for
    select using (true);

-- Create policy to allow anyone to add new todos
create policy "Anyone can add new todos" on todos for
    insert with check (true);

-- Insert sample data
insert into todos(title)
values
  ('Create Supabase project'),
  ('Create Vercel project'),
  ('Install Supabase integration');

-- ==========================================
-- VERIFICATION QUERIES
-- ==========================================
-- Uncomment the following queries to verify the setup:

-- Check if table was created successfully
-- SELECT table_name, column_name, data_type, is_nullable
-- FROM information_schema.columns
-- WHERE table_name = 'todos'
-- ORDER BY ordinal_position;

-- Check if RLS is enabled
-- SELECT schemaname, tablename, rowsecurity
-- FROM pg_tables
-- WHERE tablename = 'todos';

-- Check policies
-- SELECT schemaname, tablename, policyname, permissive, roles, cmd, qual
-- FROM pg_policies
-- WHERE tablename = 'todos';

-- View sample data
-- SELECT * FROM todos;