name: Skiftschema Scraper

on:
  workflow_dispatch: # Manuell trigger
  schedule:
    - cron: '0 2 * * *' # Kör varje dag 02:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install puppeteer-core @supabase/supabase-js dotenv

      - name: Run scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: node -r dotenv/config scripts/scrape-all.cjs