name: Skiftschema Scraper

on:
  schedule:
    # Kör varje dag kl 06:00 UTC (07:00 CET)
    - cron: '0 6 * * *'
  workflow_dispatch: # Tillåter manuell körning

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        npm install puppeteer @supabase/supabase-js node-fetch cheerio dotenv
        
    - name: Generate schemas
      run: node scripts/generate-schemas.cjs
      
    - name: Run scraper
      run: node -r dotenv/config scripts/scrape-all.cjs
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        
    - name: Notify completion
      run: echo "✅ Scraping completed successfully"