name: Skiftschema Scraper

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2:00 AM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install puppeteer@19.7.0 @supabase/supabase-js dotenv
        
      - name: Run scraping script with debugging
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          mkdir -p debug-screenshots
          node scripts/scrape-upload.cjs
          
      - name: Upload debug screenshots if failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: debug-screenshots
          path: debug-screenshots/
          retention-days: 3
